// Comprehensive question bank for GL Assessment 11+ (Year 6 level)
// 600+ unique questions across Maths, English, Verbal Reasoning, Non-Verbal Reasoning
import type { Question } from './types';

// ─── MATHS 11+ (150 questions) ───
export const CONTENT_MATHS_11PLUS: Question[] = [
  // -- Arithmetic --
  { text: 'What is 3,456 + 2,789?', options: ['5,245', '6,245', '6,345', '6,145'], correct: 1, explanation: '3,456 + 2,789 = 6,245.' },
  { text: 'What is 8,003 − 4,567?', options: ['3,536', '3,436', '3,336', '4,436'], correct: 1, explanation: '8,003 − 4,567 = 3,436.' },
  { text: 'What is 347 × 6?', options: ['2,182', '1,982', '2,082', '2,282'], correct: 2, explanation: '347 × 6 = 2,082.' },
  { text: 'What is 1,764 ÷ 12?', options: ['148', '146', '149', '147'], correct: 3, explanation: '1,764 ÷ 12 = 147.' },
  { text: 'What is 4³?', options: ['12', '64', '16', '48'], correct: 1, explanation: '4³ = 4 × 4 × 4 = 64.' },
  { text: 'What is 7²?', options: ['14', '46', '49', '72'], correct: 2, explanation: '7² = 7 × 7 = 49.' },
  { text: 'Which of these numbers is NOT prime?', options: ['7', '11', '19', '21'], correct: 3, explanation: '21 = 3 × 7, so it is not prime.' },
  { text: 'What is the highest common factor (HCF) of 24 and 36?', options: ['6', '8', '4', '12'], correct: 3, explanation: 'Factors of 24: 1,2,3,4,6,8,12,24. Factors of 36: 1,2,3,4,6,9,12,18,36. HCF = 12.' },
  { text: 'What is the lowest common multiple (LCM) of 6 and 8?', options: ['48', '12', '16', '24'], correct: 3, explanation: 'Multiples of 6: 6,12,18,24. Multiples of 8: 8,16,24. LCM = 24.' },
  { text: 'Round 4,567 to the nearest hundred.', options: ['4,500', '4,570', '4,600', '5,000'], correct: 2, explanation: '67 ≥ 50 so we round up to 4,600.' },
  { text: 'What is 1000 × 3.078?', options: ['3,078', '378', '3,708', '37.8'], correct: 0, explanation: 'Moving the decimal 3 places right: 3,078.' },
  { text: 'What is 30,785 ÷ 1000?', options: ['3.0785', '3.785', '30.785', '307.85'], correct: 2, explanation: '30,785 ÷ 1000 = 30.785.' },
  { text: 'How do you write 124 as a Roman numeral?', options: ['CXXIV', 'CXXIIII', 'CXXVI', 'LXXIV'], correct: 0, explanation: 'C=100, XX=20, IV=4. So 124 = CXXIV.' },
  { text: 'Calculate: 15 + 3 × 4', options: ['72', '27', '60', '19'], correct: 1, explanation: 'BODMAS: multiplication first. 3 × 4 = 12, then 15 + 12 = 27.' },
  { text: 'What is 256 ÷ 8?', options: ['28', '30', '32', '34'], correct: 2, explanation: '256 ÷ 8 = 32.' },
  { text: 'What is 21²?', options: ['42', '441', '4,410', '4,200'], correct: 1, explanation: '21 × 21 = 441.' },
  { text: 'Which calculation gives an odd answer?', options: ['12 × 4', '18 × 6', '9 × 3', '19 × 4'], correct: 2, explanation: '9 × 3 = 27. Odd × odd = odd.' },
  { text: 'What is −3 + 8?', options: ['−11', '5', '−5', '11'], correct: 1, explanation: '−3 + 8 = 5. Starting at −3 and moving 8 to the right.' },
  { text: 'What is −5 − (−2)?', options: ['−7', '−3', '3', '7'], correct: 1, explanation: '−5 − (−2) = −5 + 2 = −3.' },
  { text: 'What is the value of 2⁵?', options: ['10', '25', '32', '64'], correct: 2, explanation: '2⁵ = 2×2×2×2×2 = 32.' },
  { text: 'What is 4,892 + 3,108?', options: ['7,000', '8,000', '7,900', '8,100'], correct: 1, explanation: '4,892 + 3,108 = 8,000.' },
  { text: 'What is 6,000 − 2,473?', options: ['3,527', '3,427', '4,527', '3,537'], correct: 0, explanation: '6,000 − 2,473 = 3,527.' },
  { text: 'What is 235 × 14?', options: ['3,190', '3,290', '3,390', '3,490'], correct: 1, explanation: '235 × 14 = 235 × 10 + 235 × 4 = 2,350 + 940 = 3,290.' },
  { text: 'What is √144?', options: ['11', '12', '13', '14'], correct: 1, explanation: '12 × 12 = 144, so √144 = 12.' },
  { text: 'Which number is a factor of both 18 and 27?', options: ['6', '12', '9', '18'], correct: 2, explanation: '18 = 2×3², 27 = 3³. Common factor: 9.' },

  // -- Fractions, Decimals & Percentages --
  { text: 'What is 2/5 of 350?', options: ['150', '140', '130', '170'], correct: 1, explanation: '350 ÷ 5 = 70, then 70 × 2 = 140.' },
  { text: 'What is 3/4 of 80?', options: ['40', '60', '50', '70'], correct: 1, explanation: '1/4 of 80 = 20, so 3/4 = 60.' },
  { text: 'Convert 0.75 to a fraction in simplest form.', options: ['7/10', '15/20', '3/4', '6/8'], correct: 2, explanation: '0.75 = 75/100 = 3/4.' },
  { text: 'What is 15% of 240?', options: ['24', '36', '30', '48'], correct: 1, explanation: '10% = 24, 5% = 12, so 15% = 36.' },
  { text: 'Simplify: 4/6 + 1/3', options: ['5/6', '7/9', '1', '2/3'], correct: 2, explanation: '4/6 = 2/3, then 2/3 + 1/3 = 1.' },
  { text: 'What is ½ × ¾?', options: ['3/8', '3/6', '1¼', '2/6'], correct: 0, explanation: '1/2 × 3/4 = 3/8.' },
  { text: 'How many thirds are there in 12?', options: ['3', '18', '36', '48'], correct: 2, explanation: '12 ÷ (1/3) = 12 × 3 = 36.' },
  { text: 'Boris cuts his cake into 20 equal slices and gives out 16. What fraction is left?', options: ['1/5', '1/4', '2/5', '1/8'], correct: 0, explanation: '20 − 16 = 4. 4/20 = 1/5.' },
  { text: 'Tim has 42 toy cars. ⅔ are blue. How many are NOT blue?', options: ['12', '14', '16', '24'], correct: 1, explanation: '⅔ of 42 = 28 blue. 42 − 28 = 14 not blue.' },
  { text: '50 people were surveyed. 24 said black. What percentage did NOT say black?', options: ['24%', '48%', '26%', '52%'], correct: 3, explanation: '50 − 24 = 26. 26/50 = 52%.' },
  { text: 'A shop offers 20% off a £45 jacket. What is the sale price?', options: ['£38', '£40', '£35', '£36'], correct: 3, explanation: '20% of £45 = £9. £45 − £9 = £36.' },
  { text: 'Penny has 36 socks. 2/3 are white. How many white socks?', options: ['12', '18', '24', '30'], correct: 2, explanation: '2/3 of 36 = 24.' },
  { text: 'What is 0.3 × 0.4?', options: ['1.2', '0.12', '0.012', '12'], correct: 1, explanation: '3 × 4 = 12. Two decimal places total: 0.12.' },
  { text: 'Convert 7/8 to a decimal.', options: ['0.78', '0.875', '0.785', '0.8'], correct: 1, explanation: '7 ÷ 8 = 0.875.' },
  { text: 'What is 35% of 200?', options: ['35', '60', '70', '75'], correct: 2, explanation: '10% = 20, 35% = 3.5 × 20 = 70.' },
  { text: 'Which is larger: 3/5 or 7/12?', options: ['3/5', '7/12', 'They are equal', 'Cannot tell'], correct: 0, explanation: '3/5 = 36/60, 7/12 = 35/60. 36/60 > 35/60.' },
  { text: 'A price increases from £80 to £100. What is the percentage increase?', options: ['20%', '25%', '15%', '30%'], correct: 1, explanation: 'Increase = £20. 20/80 × 100 = 25%.' },
  { text: 'What is 5/6 − 1/3?', options: ['4/6', '1/2', '2/3', '1/6'], correct: 1, explanation: '1/3 = 2/6. 5/6 − 2/6 = 3/6 = 1/2.' },
  { text: 'Express 0.6 as a fraction in simplest form.', options: ['6/10', '3/5', '6/100', '60/10'], correct: 1, explanation: '0.6 = 6/10 = 3/5.' },
  { text: 'A bag has 40 sweets. 25% are red and 3/8 are blue. How many are neither?', options: ['10', '15', '20', '25'], correct: 1, explanation: 'Red: 25% of 40 = 10. Blue: 3/8 of 40 = 15. Neither: 40 − 10 − 15 = 15.' },

  // -- Geometry --
  { text: 'A regular hexagon has a perimeter of 42 cm. What is one side?', options: ['6 cm', '8 cm', '5 cm', '7 cm'], correct: 3, explanation: '42 ÷ 6 = 7 cm.' },
  { text: 'What is the area of a triangle with base 10 cm and height 6 cm?', options: ['60 cm²', '30 cm²', '16 cm²', '36 cm²'], correct: 1, explanation: 'Area = ½ × 10 × 6 = 30 cm².' },
  { text: 'A cuboid is 5 cm × 4 cm × 3 cm. What is its volume?', options: ['50 cm³', '12 cm³', '60 cm³', '24 cm³'], correct: 2, explanation: 'Volume = 5 × 4 × 3 = 60 cm³.' },
  { text: 'What does each interior angle measure in a regular hexagon?', options: ['180°', '60°', '120°', '90°'], correct: 2, explanation: 'Interior angle = (6−2) × 180 ÷ 6 = 120°.' },
  { text: 'What 3D shape has 2 circular faces and 1 curved surface?', options: ['Sphere', 'Cone', 'Cylinder', 'Cube'], correct: 2, explanation: 'A cylinder has 2 circular faces and 1 curved surface.' },
  { text: 'A rectangle has length 15 cm and width 8 cm. What is its perimeter?', options: ['23 cm', '46 cm', '120 cm', '38 cm'], correct: 1, explanation: 'Perimeter = 2(15 + 8) = 46 cm.' },
  { text: 'How many lines of symmetry does an equilateral triangle have?', options: ['1', '2', '3', '6'], correct: 2, explanation: 'An equilateral triangle has 3 lines of symmetry, one through each vertex.' },
  { text: 'What is the area of a square with side 9 cm?', options: ['18 cm²', '36 cm²', '72 cm²', '81 cm²'], correct: 3, explanation: 'Area = 9 × 9 = 81 cm².' },
  { text: 'A circle has diameter 14 cm. What is its circumference? (π ≈ 22/7)', options: ['22 cm', '44 cm', '88 cm', '28 cm'], correct: 1, explanation: 'C = π × d = 22/7 × 14 = 44 cm.' },
  { text: 'How many faces does a triangular prism have?', options: ['4', '5', '6', '3'], correct: 1, explanation: '2 triangular faces + 3 rectangular faces = 5.' },
  { text: 'What is the name of a 5-sided polygon?', options: ['Hexagon', 'Pentagon', 'Octagon', 'Heptagon'], correct: 1, explanation: 'A pentagon has 5 sides.' },
  { text: 'The angles in a triangle add up to how many degrees?', options: ['90°', '180°', '270°', '360°'], correct: 1, explanation: 'Angles in a triangle always sum to 180°.' },
  { text: 'A parallelogram has a base of 12 cm and height of 5 cm. What is its area?', options: ['17 cm²', '34 cm²', '60 cm²', '30 cm²'], correct: 2, explanation: 'Area = base × height = 12 × 5 = 60 cm².' },
  { text: 'Which 3D shape has 5 vertices?', options: ['Cube', 'Square-based pyramid', 'Triangular prism', 'Tetrahedron'], correct: 1, explanation: 'A square-based pyramid has 4 base vertices + 1 apex = 5.' },

  // -- Data Handling --
  { text: 'The scores are 4, 7, 3, 8, 3. What is the mode?', options: ['3', '4', '5', '7'], correct: 0, explanation: 'The mode is the most frequent value: 3 appears twice.' },
  { text: 'The scores are 2, 5, 8, 9, 11. What is the median?', options: ['5', '7', '8', '9'], correct: 2, explanation: 'The middle value of 5 ordered numbers is the 3rd: 8.' },
  { text: 'A fair dice is rolled. What is the probability of getting an even number?', options: ['1/6', '1/3', '1/2', '2/3'], correct: 2, explanation: 'Even numbers: 2, 4, 6 = 3 out of 6 = 1/2.' },
  { text: 'The mean of 5 numbers is 12. What is their total?', options: ['17', '60', '24', '48'], correct: 1, explanation: 'Total = mean × count = 12 × 5 = 60.' },
  { text: 'A bag has 3 red, 5 blue, and 2 green marbles. What is the probability of picking blue?', options: ['1/2', '3/10', '1/5', '5/10'], correct: 0, explanation: '5 blue out of 10 total = 5/10 = 1/2.' },
  { text: 'The range of 4, 9, 2, 15, 7 is:', options: ['9', '11', '13', '7'], correct: 2, explanation: 'Range = highest − lowest = 15 − 2 = 13.' },
  { text: 'In a bar chart, the tallest bar shows 24 children chose football. If the shortest bar shows 8 children, how many more chose football?', options: ['8', '12', '16', '32'], correct: 2, explanation: '24 − 8 = 16 more.' },
  { text: 'The mean of four numbers is 15. Three of them are 10, 18, and 12. What is the fourth?', options: ['15', '20', '25', '18'], correct: 1, explanation: 'Total = 60. 10+18+12 = 40. Fourth = 60−40 = 20.' },

  // -- Measurement --
  { text: 'How many millimetres in 3.5 cm?', options: ['3.5', '35', '350', '3,500'], correct: 1, explanation: '1 cm = 10 mm. 3.5 × 10 = 35 mm.' },
  { text: 'A train leaves at 09:45 and arrives at 11:20. How long is the journey?', options: ['1h 25m', '1h 35m', '1h 45m', '2h 05m'], correct: 1, explanation: '09:45 to 10:45 = 1h, then 10:45 to 11:20 = 35m. Total = 1h 35m.' },
  { text: 'How many grams are in 2.4 kg?', options: ['24', '240', '2,400', '24,000'], correct: 2, explanation: '1 kg = 1000 g. 2.4 × 1000 = 2,400 g.' },
  { text: 'How many minutes in 3.5 hours?', options: ['180', '200', '210', '350'], correct: 2, explanation: '3.5 × 60 = 210 minutes.' },
  { text: 'A film starts at 14:35 and lasts 1 hour 50 minutes. When does it end?', options: ['15:85', '16:25', '15:25', '16:15'], correct: 1, explanation: '14:35 + 1:50 = 15:85 → 16:25.' },
  { text: 'Convert 4,500 ml to litres.', options: ['0.45 L', '4.5 L', '45 L', '450 L'], correct: 1, explanation: '1 L = 1000 ml. 4,500 ÷ 1000 = 4.5 L.' },
  { text: '1 mile ≈ 1.6 km. About how many km is 5 miles?', options: ['6 km', '7 km', '8 km', '10 km'], correct: 2, explanation: '5 × 1.6 = 8 km.' },

  // -- Ratio & Basic Algebra --
  { text: 'Share £60 in the ratio 2:3. What is the larger share?', options: ['£24', '£30', '£36', '£40'], correct: 2, explanation: 'Total parts = 5. Each part = £12. Larger share = 3 × £12 = £36.' },
  { text: 'The ratio of boys to girls is 3:5. There are 24 students. How many girls?', options: ['9', '12', '15', '18'], correct: 2, explanation: 'Total parts = 8. Each part = 3. Girls = 5 × 3 = 15.' },
  { text: 'What is the next number in the sequence: 2, 6, 18, 54, ...?', options: ['72', '108', '162', '216'], correct: 2, explanation: 'Each number is multiplied by 3. 54 × 3 = 162.' },
  { text: 'If n = 4, what is 3n + 7?', options: ['14', '17', '19', '21'], correct: 2, explanation: '3(4) + 7 = 12 + 7 = 19.' },
  { text: 'Solve: 2x + 5 = 17', options: ['4', '5', '6', '7'], correct: 2, explanation: '2x = 12, x = 6.' },
  { text: 'A recipe needs 200g flour for 4 cakes. How much for 10 cakes?', options: ['400g', '500g', '600g', '800g'], correct: 1, explanation: '200g ÷ 4 = 50g per cake. 10 × 50g = 500g.' },
  { text: 'What is the nth term of: 5, 8, 11, 14, ...?', options: ['3n + 2', '3n + 5', 'n + 3', '2n + 3'], correct: 0, explanation: 'Goes up by 3 each time. When n=1: 3(1)+2 = 5. ✓' },
  { text: 'If 3 pencils cost £1.20, how much do 7 pencils cost?', options: ['£2.40', '£2.80', '£3.20', '£3.60'], correct: 1, explanation: '1 pencil = £0.40. 7 × £0.40 = £2.80.' },

  // -- More mixed questions --
  { text: 'What is 12.8 × 5?', options: ['60.4', '64', '64.0', '63.0'], correct: 1, explanation: '12.8 × 5 = 64.' },
  { text: 'Which is the smallest? 1/5, 0.45, 42%, 0.12', options: ['1/5', '0.45', '42%', '0.12'], correct: 3, explanation: '1/5=0.2, 42%=0.42. 0.12 is smallest.' },
  { text: 'A square has area 64 cm². What is its perimeter?', options: ['16 cm', '24 cm', '32 cm', '64 cm'], correct: 2, explanation: 'Side = √64 = 8 cm. Perimeter = 4 × 8 = 32 cm.' },
  { text: 'What number is exactly halfway between 3.6 and 4.2?', options: ['3.8', '3.9', '4.0', '3.7'], correct: 1, explanation: '(3.6 + 4.2) ÷ 2 = 7.8 ÷ 2 = 3.9.' },
  { text: 'A car travels at 60 mph for 2.5 hours. How far does it go?', options: ['120 miles', '150 miles', '125 miles', '180 miles'], correct: 1, explanation: 'Distance = speed × time = 60 × 2.5 = 150 miles.' },
  { text: 'How many vertices does a cube have?', options: ['4', '6', '8', '12'], correct: 2, explanation: 'A cube has 8 vertices.' },
  { text: 'What is 1/4 + 2/5?', options: ['3/9', '13/20', '3/20', '7/10'], correct: 1, explanation: '1/4 = 5/20, 2/5 = 8/20. 5/20 + 8/20 = 13/20.' },
  { text: 'The temperature drops from 5°C to −3°C. What is the change?', options: ['2°C', '3°C', '8°C', '−8°C'], correct: 2, explanation: '5 − (−3) = 8°C drop.' },
  { text: 'A pie chart shows 90° for "walk". What fraction walk?', options: ['1/2', '1/3', '1/4', '1/5'], correct: 2, explanation: '90° out of 360° = 1/4.' },
  { text: 'What is 999 × 7?', options: ['6,993', '6,973', '7,003', '6,983'], correct: 0, explanation: '1000 × 7 = 7000. 7000 − 7 = 6,993.' },
  { text: 'If the perimeter of an equilateral triangle is 27 cm, what is one side?', options: ['3 cm', '9 cm', '13.5 cm', '6 cm'], correct: 1, explanation: '27 ÷ 3 = 9 cm.' },
  { text: 'What is 2/3 of 90?', options: ['30', '45', '60', '75'], correct: 2, explanation: '90 ÷ 3 = 30. 30 × 2 = 60.' },
  { text: 'A number rounded to the nearest 10 is 350. What could the number be?', options: ['344', '356', '346', '355'], correct: 2, explanation: 'Numbers that round to 350 must be between 345 and 354. 346 is in this range. 344 rounds to 340, 356 rounds to 360, 355 rounds to 360.' },
  { text: 'Express 3/8 as a percentage.', options: ['33.5%', '37.5%', '38%', '36%'], correct: 1, explanation: '3 ÷ 8 = 0.375 = 37.5%.' },
  { text: 'How many edges does a cube have?', options: ['6', '8', '10', '12'], correct: 3, explanation: 'A cube has 12 edges.' },
  { text: 'A spinner has 8 equal sections, 3 are blue. What is P(not blue)?', options: ['3/8', '5/8', '1/2', '3/5'], correct: 1, explanation: 'Not blue = 8−3 = 5. P = 5/8.' },
  { text: 'Simplify 12:18', options: ['4:6', '3:4', '2:3', '6:9'], correct: 2, explanation: 'HCF of 12 and 18 is 6. 12÷6 : 18÷6 = 2:3.' },
  { text: 'What is the area of a circle with radius 7 cm? (π ≈ 22/7)', options: ['44 cm²', '154 cm²', '88 cm²', '308 cm²'], correct: 1, explanation: 'Area = πr² = 22/7 × 49 = 154 cm².' },
  { text: 'A pack of 6 drinks costs £4.50. How much per drink?', options: ['£0.65', '£0.70', '£0.75', '£0.80'], correct: 2, explanation: '£4.50 ÷ 6 = £0.75.' },
];

// ─── ENGLISH 11+ (150 questions) ───
export const CONTENT_ENGLISH_11PLUS: Question[] = [
  // -- Comprehension --
  { text: '"The old man sat alone on the bench, watching the children play. He smiled, remembering his own childhood." How does the old man feel?', options: ['Angry', 'Nostalgic', 'Frightened', 'Bored'], correct: 1, explanation: '"Remembering his own childhood" with a smile shows nostalgia — fondly recalling the past.' },
  { text: '"Despite the heavy rain, Sarah continued her walk along the cliff path." What does this tell us about Sarah?', options: ['She is careless', 'She is determined', 'She is lost', 'She enjoys rain'], correct: 1, explanation: '"Despite" shows she continues in spite of difficulty — showing determination.' },
  { text: '"The forest was silent except for the occasional crack of a twig." The word "occasional" means:', options: ['Constant', 'Happening sometimes', 'Loud', 'Frightening'], correct: 1, explanation: 'Occasional means happening from time to time, not frequently.' },
  { text: '"Maya glanced nervously at the clock. Only five minutes remained." Why is Maya nervous?', options: ['She is afraid of clocks', 'She is running out of time', 'She is lost', 'She doesn\'t like numbers'], correct: 1, explanation: 'Glancing nervously at the clock with time running out suggests she\'s worried about a deadline.' },
  { text: '"The garden had been neglected for years. Weeds choked the flower beds and the lawn was knee-high." What does "neglected" mean here?', options: ['Loved', 'Not looked after', 'Decorated', 'Planted'], correct: 1, explanation: 'The weeds and overgrown lawn show the garden has not been looked after.' },
  { text: '"Tom\'s face fell when he saw his test score." What does "his face fell" mean?', options: ['He tripped over', 'He looked disappointed', 'He was happy', 'He was confused'], correct: 1, explanation: '"Face fell" is an idiom meaning to show disappointment or sadness.' },
  { text: '"The detective examined the room carefully, noting every detail." This suggests the detective is:', options: ['Careless', 'Observant', 'Lazy', 'Confused'], correct: 1, explanation: 'Examining carefully and noting every detail shows the detective is observant.' },
  { text: '"Without a word, she turned and walked away." This suggests the character is:', options: ['Happy', 'Excited', 'Upset or angry', 'Confused'], correct: 2, explanation: 'Walking away without speaking usually indicates being upset or angry.' },
  { text: '"The sun dipped below the horizon, painting the sky in shades of orange and pink." This describes:', options: ['Sunrise', 'Sunset', 'A storm', 'Midday'], correct: 1, explanation: 'The sun going below the horizon with warm colours describes a sunset.' },
  { text: '"Liam pretended to be ill so he could stay home from school." Liam is being:', options: ['Brave', 'Honest', 'Deceptive', 'Kind'], correct: 2, explanation: 'Pretending to be ill is deceptive — he\'s not telling the truth.' },
  { text: '"The crowd erupted in cheers as the final goal was scored." "Erupted" suggests the cheering was:', options: ['Quiet', 'Sudden and loud', 'Brief', 'Angry'], correct: 1, explanation: '"Erupted" means to burst out suddenly, implying loud and enthusiastic cheering.' },
  { text: '"She whispered the secret, cupping her hand around her friend\'s ear." Why did she cup her hand?', options: ['Her hand was cold', 'To make it louder', 'So only her friend could hear', 'She was waving'], correct: 2, explanation: 'Cupping a hand around someone\'s ear while whispering keeps the message private.' },

  // -- Vocabulary --
  { text: 'Which word is a synonym for "enormous"?', options: ['Tiny', 'Huge', 'Average', 'Narrow'], correct: 1, explanation: 'Enormous and huge both mean very large.' },
  { text: 'What is the opposite of "ancient"?', options: ['Old', 'Modern', 'Rare', 'Historic'], correct: 1, explanation: '"Modern" is the antonym of "ancient".' },
  { text: 'What does "reluctant" mean?', options: ['Eager', 'Unwilling', 'Quick', 'Angry'], correct: 1, explanation: 'Reluctant means hesitant or unwilling to do something.' },
  { text: 'Which word means "to make something better"?', options: ['Worsen', 'Improve', 'Destroy', 'Ignore'], correct: 1, explanation: 'Improve means to make something better.' },
  { text: 'What is a synonym for "courageous"?', options: ['Scared', 'Brave', 'Weak', 'Lazy'], correct: 1, explanation: 'Courageous and brave both mean showing bravery.' },
  { text: 'The word "annual" means:', options: ['Monthly', 'Weekly', 'Yearly', 'Daily'], correct: 2, explanation: 'Annual means happening once every year.' },
  { text: 'What is the antonym of "generous"?', options: ['Kind', 'Selfish', 'Wealthy', 'Happy'], correct: 1, explanation: 'Generous means giving freely; selfish means the opposite.' },
  { text: 'Which word means "easily broken"?', options: ['Durable', 'Flexible', 'Fragile', 'Sturdy'], correct: 2, explanation: 'Fragile means delicate and easily broken.' },
  { text: '"The children were jubilant." This means they were:', options: ['Sad', 'Extremely happy', 'Tired', 'Confused'], correct: 1, explanation: 'Jubilant means feeling great happiness and triumph.' },
  { text: 'What does "frequent" mean?', options: ['Rare', 'Happening often', 'Slow', 'Interesting'], correct: 1, explanation: 'Frequent means occurring regularly or many times.' },
  { text: 'Which word is closest in meaning to "peculiar"?', options: ['Normal', 'Strange', 'Beautiful', 'Simple'], correct: 1, explanation: 'Peculiar means strange or unusual.' },
  { text: 'What is the meaning of "habitat"?', options: ['A bad habit', 'The natural home of an animal', 'A type of clothing', 'A kind of food'], correct: 1, explanation: 'A habitat is the natural environment where an animal lives.' },
  { text: 'What is the antonym of "transparent"?', options: ['Clear', 'Opaque', 'Shiny', 'Thin'], correct: 1, explanation: 'Transparent means see-through; opaque means you cannot see through it.' },
  { text: 'Which word means "to go down"?', options: ['Ascend', 'Descend', 'Attend', 'Suspend'], correct: 1, explanation: 'Descend means to go or move down.' },

  // -- Punctuation & Grammar --
  { text: 'Which sentence is punctuated correctly?', options: ['where are you going', 'Where are you going?', 'Where are you going.', 'where are you going?'], correct: 1, explanation: 'Questions start with a capital letter and end with a question mark.' },
  { text: 'Where should the apostrophe go? "The dogs bone was buried."', options: ['dog\'s', 'dogs\'', 'dogs', 'No apostrophe needed'], correct: 0, explanation: 'One dog owns the bone, so it\'s "the dog\'s bone" (singular possessive).' },
  { text: 'Which sentence uses a comma correctly?', options: ['I like cats, dogs and fish.', 'I like, cats dogs and fish.', 'I, like cats dogs and fish.', 'I like cats dogs, and fish.'], correct: 0, explanation: 'Commas separate items in a list: "cats, dogs and fish."' },
  { text: 'Choose the correct sentence:', options: ['Their going to the park.', 'They\'re going to the park.', 'There going to the park.', 'Theyre going to the park.'], correct: 1, explanation: '"They\'re" is short for "they are." "Their" = belonging to them. "There" = a place.' },
  { text: 'Which word completes the sentence? "The children ___ playing in the garden."', options: ['was', 'were', 'is', 'am'], correct: 1, explanation: '"Children" is plural, so we use "were" (plural past tense).' },
  { text: 'Which sentence needs a colon?', options: ['She bought apples oranges and bananas.', 'She bought three fruits apples oranges and bananas.', 'She bought the following items apples, oranges and bananas.', 'She bought apples, oranges and bananas from the shop.'], correct: 2, explanation: 'A colon introduces a list: "She bought the following items: apples, oranges and bananas."' },
  { text: 'Which is the correct use of speech marks?', options: ['"Hello," said Tom.', '"Hello", said Tom.', '"Hello" said Tom.', 'Hello, "said Tom."'], correct: 0, explanation: 'The comma goes inside the speech marks before the reporting clause.' },
  { text: 'Identify the adverb in: "She ran quickly to the shop."', options: ['She', 'ran', 'quickly', 'shop'], correct: 2, explanation: '"Quickly" describes how she ran — it\'s an adverb modifying the verb.' },
  { text: 'Which sentence is in the passive voice?', options: ['The cat chased the mouse.', 'The mouse was chased by the cat.', 'The cat is chasing.', 'The cat will chase the mouse.'], correct: 1, explanation: 'Passive voice: the subject receives the action. "The mouse was chased."' },
  { text: 'Choose the correct sentence:', options: ['I could of gone.', 'I could have gone.', 'I could\'ve went.', 'I could has gone.'], correct: 1, explanation: '"Could have" is correct. "Could of" is a common mistake.' },
  { text: '"The boy who broke the window ran away." The relative clause is:', options: ['The boy', 'who broke the window', 'ran away', 'the window'], correct: 1, explanation: '"Who broke the window" is a relative clause giving extra information about the boy.' },
  { text: 'Which sentence uses a semicolon correctly?', options: ['It was raining; we stayed inside.', 'It was; raining we stayed inside.', 'It was raining we; stayed inside.', 'It; was raining we stayed inside.'], correct: 0, explanation: 'A semicolon joins two closely related independent clauses.' },
  { text: 'What type of word is "beautiful"?', options: ['Noun', 'Verb', 'Adjective', 'Adverb'], correct: 2, explanation: '"Beautiful" describes a noun — it\'s an adjective.' },
  { text: 'Which is the correct plural?', options: ['Childs', 'Childrens', 'Children', 'Childes'], correct: 2, explanation: '"Children" is the irregular plural of "child."' },
  { text: '"I enjoy swimming, cycling and reading." What type of sentence is this?', options: ['Question', 'Command', 'Statement', 'Exclamation'], correct: 2, explanation: 'It states a fact about what the person enjoys — it\'s a statement.' },
  { text: 'Choose the correct word: "The team ___ won the match."', options: ['who', 'which', 'that', 'whom'], correct: 2, explanation: '"That" or "which" can introduce a defining relative clause about a team.' },
  { text: 'Where should the comma go? "After eating the children went outside."', options: ['After, eating the children went outside.', 'After eating, the children went outside.', 'After eating the children, went outside.', 'After eating the, children went outside.'], correct: 1, explanation: 'A comma after the fronted adverbial "After eating" separates it from the main clause.' },

  // -- Spelling & Error Spotting --
  { text: 'Which word is spelled correctly?', options: ['Recieve', 'Receive', 'Receve', 'Receeve'], correct: 1, explanation: 'Remember: "i before e except after c" — Receive.' },
  { text: 'Which word is misspelled?', options: ['Beautiful', 'Definately', 'Separate', 'Necessary'], correct: 1, explanation: 'The correct spelling is "Definitely" not "Definately."' },
  { text: 'Spot the error: "The childrens toys were scattered across the room."', options: ['childrens should be children\'s', 'toys should be toy\'s', 'were should be was', 'No error'], correct: 0, explanation: '"Children" is already plural, so the possessive is "children\'s."' },
  { text: 'Which is the correct spelling?', options: ['Goverment', 'Government', 'Govenment', 'Govurnment'], correct: 1, explanation: 'Government is the correct spelling — remember the "n" before "ment."' },
  { text: 'Spot the mistake: "Me and Tom went to the shops."', options: ['Me should be I', 'Tom should be tom', 'went should be gone', 'shops should be shop'], correct: 0, explanation: '"Tom and I went" is correct. "I" is used as the subject, not "me."' },
  { text: 'Which word is spelled correctly?', options: ['Accomodation', 'Accommodation', 'Acomodation', 'Acommodation'], correct: 1, explanation: 'Accommodation has two c\'s and two m\'s.' },
  { text: 'Which sentence has a spelling error?', options: ['The weather was terrible.', 'She was very independant.', 'He gave a separate answer.', 'The rhythm was perfect.'], correct: 1, explanation: 'The correct spelling is "independent" not "independant."' },
  { text: 'Spot the error: "Their are three cats on the wall."', options: ['Their should be There', 'are should be is', 'three should be 3', 'No error'], correct: 0, explanation: '"There are" is correct for indicating existence. "Their" = belonging to them.' },
  { text: 'Which word is spelled correctly?', options: ['Occured', 'Occurred', 'Ocurred', 'Ocured'], correct: 1, explanation: 'Occurred has two c\'s and two r\'s.' },
  { text: 'Spot the error: "The boy done his homework quickly."', options: ['boy should be Boy', 'done should be did', 'his should be he\'s', 'quickly should be quick'], correct: 1, explanation: '"Did" is the correct past tense. "Done" needs a helper: "has done."' },
  { text: 'Which is correct?', options: ['alot of people', 'a lot of people', 'allot of people', 'alott of people'], correct: 1, explanation: '"A lot" is always two words. "Alot" is not a word.' },
  { text: 'Which word is spelled correctly?', options: ['Enviroment', 'Environment', 'Envirement', 'Envirnoment'], correct: 1, explanation: 'Environment — remember the "n" before "ment."' },

  // -- Literary Devices --
  { text: 'Which is a noun?', options: ['Quickly', 'Happiness', 'Green', 'Run'], correct: 1, explanation: '"Happiness" names a thing (an emotion) — it\'s a noun.' },
  { text: '"The wind howled through the trees." This is an example of:', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], correct: 2, explanation: 'The wind is given a human action (howling) — personification.' },
  { text: '"She was as brave as a lion." This is a:', options: ['Metaphor', 'Simile', 'Personification', 'Hyperbole'], correct: 1, explanation: 'Uses "as...as" to compare — this is a simile.' },
  { text: '"Peter Piper picked a peck of pickled peppers." This uses:', options: ['Simile', 'Metaphor', 'Alliteration', 'Onomatopoeia'], correct: 2, explanation: 'The repeated "p" sound at the start of words is alliteration.' },
  { text: '"The classroom was a zoo." This is a:', options: ['Simile', 'Metaphor', 'Hyperbole', 'Alliteration'], correct: 1, explanation: 'Directly calling the classroom a zoo (without "like" or "as") is a metaphor.' },
  { text: '"I\'ve told you a million times!" This is:', options: ['A fact', 'Hyperbole', 'A simile', 'Personification'], correct: 1, explanation: 'Exaggerating for effect ("a million times") is hyperbole.' },
  { text: '"The fire crackled and popped." "Crackled" is an example of:', options: ['Simile', 'Alliteration', 'Onomatopoeia', 'Metaphor'], correct: 2, explanation: '"Crackled" imitates the sound a fire makes — onomatopoeia.' },

  // -- More comprehension & grammar --
  { text: 'What is a prefix?', options: ['A word ending', 'A group of letters added to the start of a word', 'A type of punctuation', 'A full sentence'], correct: 1, explanation: 'A prefix is added to the beginning of a word to change its meaning (e.g., un-, re-, pre-).' },
  { text: 'Add the correct prefix to "happy" to make its opposite:', options: ['unhappy', 'dishappy', 'inhappy', 'mishappy'], correct: 0, explanation: '"Un-" is the correct prefix: unhappy.' },
  { text: 'What does the suffix "-ful" mean in "hopeful"?', options: ['Without', 'Full of', 'Before', 'Against'], correct: 1, explanation: '"-ful" means "full of" — hopeful means full of hope.' },
  { text: 'Which sentence is a command?', options: ['Where is the library?', 'The library is closed.', 'Close the door quietly.', 'What a beautiful day!'], correct: 2, explanation: 'A command (imperative) tells someone to do something: "Close the door."' },
  { text: 'Which word is a conjunction?', options: ['Because', 'Quickly', 'Happy', 'Table'], correct: 0, explanation: 'Conjunctions (because, and, but, or) join words, phrases, or clauses.' },
  { text: '"The ancient castle loomed above the village." What does "loomed" suggest?', options: ['It was small', 'It appeared large and threatening', 'It was far away', 'It was hidden'], correct: 1, explanation: '"Loomed" suggests something appearing large, imposing, and possibly threatening.' },
  { text: 'Which word class does "under" belong to?', options: ['Noun', 'Verb', 'Preposition', 'Adjective'], correct: 2, explanation: '"Under" shows position/relation — it\'s a preposition.' },
  { text: 'What is the past tense of "write"?', options: ['Writed', 'Wrote', 'Written', 'Writing'], correct: 1, explanation: 'The simple past tense of "write" is "wrote." "Written" is the past participle.' },
  { text: 'Which is a compound sentence?', options: ['The dog barked.', 'The dog barked and the cat ran.', 'The big brown dog barked loudly.', 'Barking loudly, the dog ran.'], correct: 1, explanation: 'Two independent clauses joined by "and" make a compound sentence.' },
];

// ─── VERBAL REASONING 11+ (160 questions) ───
export const CONTENT_VERBAL_11PLUS: Question[] = [
  // -- Word Meanings & Analogies --
  { text: 'Find the odd one out: Apple, Banana, Carrot, Mango, Grape', options: ['Apple', 'Banana', 'Carrot', 'Mango'], correct: 2, explanation: 'Carrot is a vegetable; the others are all fruits.' },
  { text: 'Complete the analogy: Hot is to Cold as Day is to ___', options: ['Light', 'Night', 'Sun', 'Warm'], correct: 1, explanation: 'Hot and Cold are opposites, so Day and Night are opposites.' },
  { text: 'Which word is most OPPOSITE in meaning to "brave"?', options: ['Strong', 'Cowardly', 'Angry', 'Calm'], correct: 1, explanation: 'Brave means courageous; cowardly means lacking courage.' },
  { text: 'Find the odd one out: Square, Circle, Triangle, Cube, Rectangle', options: ['Square', 'Circle', 'Cube', 'Rectangle'], correct: 2, explanation: 'Cube is a 3D shape; the others are all 2D shapes.' },
  { text: 'Complete: Doctor is to Hospital as Teacher is to ___', options: ['Students', 'School', 'Books', 'Classroom'], correct: 1, explanation: 'A doctor works in a hospital, a teacher works in a school.' },
  { text: 'Which word is closest in meaning to "begin"?', options: ['End', 'Start', 'Continue', 'Stop'], correct: 1, explanation: 'Begin and start mean the same thing.' },
  { text: 'Find the odd one out: Violin, Trumpet, Flute, Piano, Brush', options: ['Violin', 'Trumpet', 'Piano', 'Brush'], correct: 3, explanation: 'Brush is not a musical instrument; the others are.' },
  { text: 'Complete: Calf is to Cow as Kitten is to ___', options: ['Dog', 'Cat', 'Puppy', 'Lamb'], correct: 1, explanation: 'A calf is a young cow; a kitten is a young cat.' },
  { text: 'Which word means the same as "angry"?', options: ['Happy', 'Furious', 'Calm', 'Sleepy'], correct: 1, explanation: 'Furious means extremely angry.' },
  { text: 'Find the odd one out: Mars, Jupiter, Moon, Saturn, Neptune', options: ['Mars', 'Jupiter', 'Moon', 'Saturn'], correct: 2, explanation: 'Moon is a satellite; the others are planets.' },
  { text: 'Complete: Pen is to Write as Knife is to ___', options: ['Sharp', 'Fork', 'Cut', 'Kitchen'], correct: 2, explanation: 'You use a pen to write and a knife to cut.' },
  { text: 'Which word is most OPPOSITE to "generous"?', options: ['Kind', 'Mean', 'Rich', 'Happy'], correct: 1, explanation: 'Generous means giving freely; mean (stingy) is the opposite.' },
  { text: 'Find the odd one out: Oak, Elm, Rose, Birch, Willow', options: ['Oak', 'Rose', 'Birch', 'Willow'], correct: 1, explanation: 'Rose is a flower; the others are all trees.' },
  { text: 'Complete: Eye is to See as Ear is to ___', options: ['Sound', 'Hear', 'Nose', 'Music'], correct: 1, explanation: 'Eyes are for seeing; ears are for hearing.' },
  { text: 'Which word means the same as "assist"?', options: ['Prevent', 'Help', 'Hinder', 'Ignore'], correct: 1, explanation: 'Assist and help both mean to give support.' },
  { text: 'Find the odd one out: London, Paris, France, Berlin, Tokyo', options: ['London', 'Paris', 'France', 'Berlin'], correct: 2, explanation: 'France is a country; the others are capital cities.' },
  { text: 'Complete: Bird is to Feather as Fish is to ___', options: ['Water', 'Scale', 'Fin', 'Swim'], correct: 1, explanation: 'Birds are covered in feathers; fish are covered in scales.' },
  { text: 'Which word is OPPOSITE to "permanent"?', options: ['Lasting', 'Temporary', 'Strong', 'Fixed'], correct: 1, explanation: 'Permanent means lasting forever; temporary means lasting a short time.' },
  { text: 'Which word can mean both "a type of animal" and "to carry"?', options: ['Bear', 'Duck', 'Bat', 'Crane'], correct: 0, explanation: 'Bear (noun) is an animal; bear (verb) means to carry or endure.' },
  { text: 'Which word can mean both "not heavy" and "brightness"?', options: ['Weight', 'Light', 'Dark', 'Bright'], correct: 1, explanation: 'Light can mean not heavy (adj) or brightness/illumination (noun).' },

  // -- Word Codes & Hidden Words --
  { text: 'If CAT = 3,1,20 (A=1, B=2...), what does DOG equal?', options: ['4,15,7', '4,14,7', '3,15,7', '4,15,6'], correct: 0, explanation: 'D=4, O=15, G=7. So DOG = 4,15,7.' },
  { text: 'Find the hidden word in: "The boy ran to the BEACH, AIR blowing his hair."', options: ['CHAIR', 'HAIR', 'BEACH', 'EACH'], correct: 0, explanation: 'beaCH AIR — the hidden word spanning two words is CHAIR.' },
  { text: 'If FISH = GJTI (each letter moves forward 1), what does BIRD become?', options: ['CJSE', 'CHQC', 'CJSD', 'CKSE'], correct: 0, explanation: 'B→C, I→J, R→S, D→E. BIRD becomes CJSE.' },
  { text: 'Which word means the OPPOSITE of ANCIENT?', options: ['Old', 'Historic', 'Modern', 'Classic'], correct: 2, explanation: 'Ancient means very old, so MODERN (current, new) is the opposite.' },
  { text: 'If the code for BLUE is 2,12,21,5, what letter does 8 represent?', options: ['F', 'G', 'H', 'I'], correct: 2, explanation: 'A=1, B=2, C=3... H=8.' },
  { text: 'Find a word that can go BEFORE each: ___LIGHT, ___SHINE, ___BURN', options: ['FIRE', 'SUN', 'MOON', 'STAR'], correct: 1, explanation: 'SUNLIGHT, SUNSHINE, SUNBURN — all real words.' },
  { text: 'Find a word that can go BEFORE each: ___LIGHT, ___RISE, ___SET', options: ['MOON', 'STAR', 'SUN', 'DAY'], correct: 2, explanation: 'SUNLIGHT, SUNRISE, SUNSET — SUN goes before all three words.' },
  { text: 'Which letter comes next in the pattern: A, C, E, G, ?', options: ['H', 'I', 'J', 'K'], correct: 1, explanation: 'The pattern skips one letter each time: A(+2)C(+2)E(+2)G(+2)I.' },

  // -- Number & Letter Sequences --
  { text: 'What comes next: 3, 6, 12, 24, ?', options: ['30', '36', '48', '52'], correct: 2, explanation: 'Each number doubles: 24 × 2 = 48.' },
  { text: 'What comes next: 2, 5, 10, 17, 26, ?', options: ['33', '35', '37', '39'], correct: 2, explanation: 'Differences: +3, +5, +7, +9, +11. So 26 + 11 = 37.' },
  { text: 'What comes next: 1, 1, 2, 3, 5, 8, ?', options: ['11', '12', '13', '14'], correct: 2, explanation: 'Fibonacci sequence: each number is the sum of the two before. 5+8 = 13.' },
  { text: 'What is the next letter: B, D, F, H, ?', options: ['I', 'J', 'K', 'L'], correct: 1, explanation: 'Every second letter: B, D, F, H, J.' },
  { text: 'What comes next: 100, 95, 89, 82, ?', options: ['76', '75', '74', '73'], correct: 2, explanation: 'Differences: −5, −6, −7, −8. So 82 − 8 = 74.' },
  { text: 'What comes next: 1, 4, 9, 16, 25, ?', options: ['30', '35', '36', '49'], correct: 2, explanation: 'These are square numbers: 1², 2², 3², 4², 5², 6²=36.' },
  { text: 'Complete the sequence: AZ, BY, CX, DW, ?', options: ['EV', 'EU', 'EX', 'FV'], correct: 0, explanation: 'First letter goes forward (A,B,C,D,E), second goes backward (Z,Y,X,W,V). Answer: EV.' },
  { text: 'What comes next: 2, 6, 18, 54, ?', options: ['108', '162', '180', '216'], correct: 1, explanation: 'Each number is multiplied by 3. 54 × 3 = 162.' },
  { text: 'What comes next: 64, 32, 16, 8, ?', options: ['2', '4', '6', '0'], correct: 1, explanation: 'Each number is halved: 8 ÷ 2 = 4.' },
  { text: 'What number is missing: 3, 7, ?, 15, 19', options: ['9', '10', '11', '12'], correct: 2, explanation: 'The pattern adds 4 each time: 3, 7, 11, 15, 19.' },

  // -- Logic & Deduction --
  { text: 'All roses are flowers. Some flowers are red. Which MUST be true?', options: ['All roses are red', 'Some roses are red', 'Roses are flowers', 'All flowers are roses'], correct: 2, explanation: 'We know for certain that all roses are flowers — that was stated directly.' },
  { text: 'Amy is taller than Beth. Beth is taller than Cara. Who is shortest?', options: ['Amy', 'Beth', 'Cara', 'Cannot tell'], correct: 2, explanation: 'Amy > Beth > Cara. Cara is the shortest.' },
  { text: 'If it is Monday, then the shop is closed. The shop is open. What day is it?', options: ['Monday', 'Not Monday', 'Tuesday', 'Cannot tell'], correct: 1, explanation: 'If Monday → closed. Shop is open, so it is NOT Monday.' },
  { text: 'Tom has more sweets than Harry. Harry has more sweets than Sam. Sam has 5 sweets. Tom has 12. How many might Harry have?', options: ['4', '13', '8', '3'], correct: 2, explanation: 'Harry must have more than 5 (Sam) and fewer than 12 (Tom). Only 8 fits.' },
  { text: 'All cats have tails. Whiskers is a cat. What can we conclude?', options: ['Whiskers likes milk', 'Whiskers is fluffy', 'Whiskers has a tail', 'Whiskers is small'], correct: 2, explanation: 'All cats have tails + Whiskers is a cat = Whiskers has a tail.' },
  { text: 'In a race, Dan finished before Emily but after Ben. Who came second?', options: ['Ben', 'Dan', 'Emily', 'Cannot tell'], correct: 1, explanation: 'Order: Ben, Dan, Emily. Dan came second.' },
  { text: 'If all X are Y, and all Y are Z, which must be true?', options: ['All Z are X', 'All X are Z', 'Some Z are not Y', 'All Y are X'], correct: 1, explanation: 'X⊆Y and Y⊆Z means X⊆Z. All X are Z.' },
  { text: 'There are 5 houses in a row. The red house is next to the blue house. The blue house is in the middle. The green house is at one end. Where could the red house be?', options: ['Position 1', 'Position 2 or 4', 'Position 5', 'Position 3'], correct: 1, explanation: 'Blue is in position 3 (middle). Red is next to blue, so position 2 or 4.' },
  { text: 'Sarah is older than 10 but younger than 15. Her age is even. She is not 12. How old is Sarah?', options: ['11', '13', '14', '10'], correct: 2, explanation: 'Between 10-15, even, not 12: only 14 fits.' },
  { text: 'No birds are mammals. A robin is a bird. Which must be true?', options: ['A robin is a mammal', 'A robin is not a mammal', 'All birds are robins', 'Some mammals are birds'], correct: 1, explanation: 'No birds are mammals + robin is a bird = robin is not a mammal.' },

  // -- Anagrams & Rearrangement --
  { text: 'Rearrange the letters CHEAT to make another word:', options: ['TEACH', 'CATCH', 'CHEAP', 'EACH'], correct: 0, explanation: 'CHEAT rearranged gives TEACH.' },
  { text: 'Rearrange LISTEN to make another word:', options: ['INSTLE', 'SILENT', 'LENTIS', 'TINSEL'], correct: 1, explanation: 'LISTEN rearranged gives SILENT.' },
  { text: 'Rearrange EARTH to make another word:', options: ['HEART', 'HEATH', 'HATER', 'THREE'], correct: 0, explanation: 'EARTH rearranged gives HEART.' },
  { text: 'Rearrange SHELF to make another word:', options: ['FLESH', 'FRESH', 'SHELF', 'HELPS'], correct: 0, explanation: 'SHELF rearranged gives FLESH.' },
  { text: 'Rearrange BELOW to make another word:', options: ['BOWEL', 'BLOWN', 'ELBOW', 'TOWEL'], correct: 2, explanation: 'BELOW rearranged gives ELBOW.' },
  { text: 'Rearrange SPARE to make another words:', options: ['PEARS', 'SPEAR', 'PARSE', 'All of these'], correct: 3, explanation: 'SPARE can be rearranged into PEARS, SPEAR, and PARSE.' },
  { text: 'Rearrange BAKER to make another word:', options: ['BREAK', 'BRAKE', 'BAKE', 'RAKE'], correct: 0, explanation: 'BAKER rearranged gives BREAK.' },
  { text: 'Rearrange LEMON to make another word:', options: ['MELON', 'MONEL', 'LEMON', 'MONEL'], correct: 0, explanation: 'LEMON rearranged gives MELON.' },
  { text: 'Rearrange GROAN to make another word:', options: ['ORANGE', 'ORGAN', 'ARGON', 'RANGE'], correct: 1, explanation: 'GROAN rearranged gives ORGAN.' },
  { text: 'Rearrange STONE to make another word:', options: ['TONES', 'NOTES', 'ONSET', 'All of these'], correct: 3, explanation: 'STONE can make TONES, NOTES, and ONSET.' },

  // -- More mixed VR --
  { text: 'Which two words are most similar in meaning? FAST, SLOW, QUICK, HEAVY', options: ['FAST and SLOW', 'FAST and QUICK', 'SLOW and HEAVY', 'QUICK and HEAVY'], correct: 1, explanation: 'FAST and QUICK both mean moving with speed.' },
  { text: 'Which two words are most opposite? BRIGHT, DARK, LIGHT, HEAVY', options: ['BRIGHT and DARK', 'BRIGHT and LIGHT', 'LIGHT and HEAVY', 'DARK and HEAVY'], correct: 0, explanation: 'BRIGHT and DARK are opposites.' },
  { text: 'Complete: BOOK is to READING as FORK is to ___', options: ['KNIFE', 'EATING', 'COOKING', 'FOOD'], correct: 1, explanation: 'A book is used for reading; a fork is used for eating.' },
  { text: 'Find the odd one out: POTATO, ONION, APPLE, CARROT, BEETROOT', options: ['POTATO', 'ONION', 'APPLE', 'CARROT'], correct: 2, explanation: 'APPLE is a fruit; the others are vegetables.' },
  { text: 'If JUMP = KVNQ (each letter +1), decode DPPM:', options: ['COOL', 'BOOM', 'BOOK', 'COOK'], correct: 0, explanation: 'D→C, P→O, P→O, M→L. DPPM decodes to COOL.' },
  { text: 'What comes next: Z, X, V, T, ?', options: ['S', 'R', 'Q', 'P'], correct: 1, explanation: 'Going backward, skipping one letter: Z, X, V, T, R.' },
  { text: 'Complete the analogy: TALL is to SHORT as WIDE is to ___', options: ['BIG', 'NARROW', 'THIN', 'LONG'], correct: 1, explanation: 'Tall and short are opposites describing height. Wide and NARROW are opposites describing width.' },
  { text: 'Which word means the SAME as RAPID?', options: ['Slow', 'Quick', 'Careful', 'Heavy'], correct: 1, explanation: 'Rapid and quick both mean fast.' },
  { text: 'Complete: NOSE is to SMELL as TONGUE is to ___', options: ['MOUTH', 'TASTE', 'FOOD', 'LICK'], correct: 1, explanation: 'The nose is for smelling; the tongue is for tasting.' },
  { text: 'Which letter is 5th from the end of the alphabet?', options: ['V', 'W', 'U', 'T'], correct: 0, explanation: 'Counting back from Z: Z(1), Y(2), X(3), W(4), V(5).' },

  // Extra VR
  { text: 'Which word means the OPPOSITE of "ancient"?', options: ['Old', 'Modern', 'Historical', 'Classic'], correct: 1, explanation: 'Ancient means very old; modern means recent or new.' },
  { text: 'Complete: HAND is to GLOVE as FOOT is to ___', options: ['LEG', 'SHOE', 'TOE', 'SOCK'], correct: 1, explanation: 'A glove covers a hand; a shoe covers a foot.' },
  { text: 'Find the odd one out: PARIS, LONDON, ENGLAND, ROME, MADRID', options: ['PARIS', 'LONDON', 'ENGLAND', 'ROME'], correct: 2, explanation: 'ENGLAND is a country; the others are capital cities.' },
  { text: 'What comes next in the pattern: 1, 3, 6, 10, 15, ?', options: ['18', '20', '21', '25'], correct: 2, explanation: 'Triangle numbers. Differences increase by 1: +2,+3,+4,+5,+6. 15+6=21.' },
  { text: 'If CAR costs £3+£1+£18=£22 (A=1..Z=26), how much does BUS cost?', options: ['£38', '£40', '£42', '£44'], correct: 2, explanation: 'B=2, U=21, S=19. Total = 2+21+19 = £42.' },
  { text: 'Which two words are most OPPOSITE? ACCEPT, DECLINE, RECEIVE, GIVE', options: ['ACCEPT and DECLINE', 'ACCEPT and RECEIVE', 'DECLINE and GIVE', 'RECEIVE and GIVE'], correct: 0, explanation: 'Accept means to say yes; decline means to say no. They are opposites.' },
  { text: 'Complete: PAINTER is to BRUSH as WRITER is to ___', options: ['BOOK', 'PEN', 'PAPER', 'STORY'], correct: 1, explanation: 'A painter uses a brush; a writer uses a pen.' },
  { text: 'Rearrange the letters PLATES to make another word:', options: ['STAPLE', 'PETALS', 'PASTEL', 'All of these'], correct: 3, explanation: 'PLATES can be rearranged into STAPLE, PETALS, and PASTEL.' },
  { text: 'What number comes next: 81, 27, 9, 3, ?', options: ['0', '1', '2', '3'], correct: 1, explanation: 'Each number is divided by 3: 3 ÷ 3 = 1.' },
  { text: 'Find the odd one out: MERCURY, LEAD, IRON, TENNIS, COPPER', options: ['MERCURY', 'LEAD', 'TENNIS', 'COPPER'], correct: 2, explanation: 'TENNIS is a sport; the others are metals/elements.' },
];

// ─── NON-VERBAL REASONING 11+ (160 questions — text-described) ───
export const CONTENT_NVR_11PLUS: Question[] = [
  // -- Pattern & Series --
  { text: 'In a sequence, each shape gains one extra side: triangle, square, pentagon. What comes next?', options: ['Hexagon (6 sides)', 'Circle', 'Octagon', 'Diamond'], correct: 0, explanation: '3 sides, 4 sides, 5 sides — next is 6 sides: hexagon.' },
  { text: 'In a pattern, a black dot moves one corner clockwise around a square. After 4 moves, where is it?', options: ['Top-left (start position)', 'Top-right', 'Bottom-right', 'Bottom-left'], correct: 0, explanation: 'Moving clockwise around 4 corners returns to the start after 4 moves.' },
  { text: 'Each shape in the sequence gets one more dot inside: 1 dot, 2 dots, 3 dots. The shapes alternate between circle and square. What is the 6th shape?', options: ['Circle with 6 dots', 'Square with 6 dots', 'Circle with 5 dots', 'Square with 5 dots'], correct: 1, explanation: 'Pattern: Circle(1), Square(2), Circle(3), Square(4), Circle(5), Square(6).' },
  { text: 'A shape rotates 90° clockwise each step. It starts pointing up. After 3 rotations, which way does it point?', options: ['Up', 'Right', 'Down', 'Left'], correct: 3, explanation: 'Up → Right (90°) → Down (180°) → Left (270°).' },
  { text: 'In a sequence, shapes alternate between shaded and unshaded. The sizes go: small, medium, large, small, medium, large. What is the 5th shape?', options: ['Shaded medium', 'Unshaded medium', 'Shaded small', 'Unshaded large'], correct: 0, explanation: 'Shading alternates: Shaded, Unshaded, Shaded, Unshaded, Shaded. Position 5 is shaded. Size cycles: S, M, L, S, M. Position 5 is medium. So the 5th shape is Shaded medium.' },
  { text: 'A triangle points up, then down, then up. If this pattern continues, which way does the 8th triangle point?', options: ['Up', 'Down', 'Left', 'Right'], correct: 1, explanation: 'Odd positions point up, even positions point down. 8 is even, so down.' },
  { text: 'In each step, a line is added to form a shape: 1 line, 2 lines (angle), 3 lines (triangle). How many lines make the next step?', options: ['3', '4', '5', '6'], correct: 1, explanation: 'Each step adds 1 line: 1, 2, 3, 4 lines (making a square).' },
  { text: 'A dot starts in the centre of a grid and moves: right, up, left, up. Where is it now relative to the start?', options: ['One square up', 'Two squares up', 'Same position', 'One square left and two up'], correct: 1, explanation: 'Right then left cancel out. Up twice = two squares up from centre.' },
  { text: 'In a pattern, shapes grow by one unit each time: 1×1 square, 2×2 square, 3×3 square. How many small squares are in the 4th shape?', options: ['8', '12', '16', '20'], correct: 2, explanation: '4×4 = 16 small squares.' },
  { text: 'A shape is white, then grey, then black, then white again. What shade is the 10th shape?', options: ['White', 'Grey', 'Black', 'Cannot tell'], correct: 0, explanation: 'The cycle repeats every 3: positions 1,4,7,10 are white.' },

  // -- Odd One Out --
  { text: 'Four shapes are circles and one is an oval. Which property makes the oval the odd one out?', options: ['It has no corners', 'It is not perfectly round', 'It has edges', 'It is 2D'], correct: 1, explanation: 'An oval is elongated, not perfectly round like a circle.' },
  { text: 'Four shapes have straight edges only. One has a curved edge. Which is the odd one out?', options: ['The one with a curved edge', 'The biggest one', 'The smallest one', 'The shaded one'], correct: 0, explanation: 'The shape with a curved edge is different from all shapes with only straight edges.' },
  { text: 'Four shapes are shaded with horizontal lines. One is shaded with vertical lines. Which is the odd one out?', options: ['A horizontal one', 'The vertical one', 'The biggest one', 'None'], correct: 1, explanation: 'The vertical line shading makes it different from all horizontal ones.' },
  { text: 'Four shapes have an even number of sides. One has an odd number. Which is the odd one out?', options: ['Square', 'Hexagon', 'Triangle', 'Octagon'], correct: 2, explanation: 'Triangle has 3 sides (odd). Square(4), Hexagon(6), Octagon(8) are all even.' },
  { text: 'Four shapes contain a small circle inside. One contains a small triangle inside. Which is the odd one out?', options: ['Shape with the small triangle', 'The largest outer shape', 'The smallest outer shape', 'The darkest shape'], correct: 0, explanation: 'The internal shape differs — small triangle vs small circles.' },
  { text: 'Four arrows point in cardinal directions (N, S, E, W). One points diagonally (NE). Which is the odd one out?', options: ['North', 'South', 'North-East', 'West'], correct: 2, explanation: 'NE is diagonal; the others are cardinal (straight) directions.' },
  { text: 'In a group of shapes, four have rotational symmetry but one does not. The one without rotational symmetry is:', options: ['A square', 'An equilateral triangle', 'A circle', 'A scalene triangle'], correct: 3, explanation: 'A scalene triangle has no rotational symmetry (all sides different).' },
  { text: 'Four shapes have exactly 1 line of symmetry. One has exactly 2. Which is the odd one out?', options: ['Isosceles triangle', 'Rectangle (not square)', 'Kite', 'Arrow shape'], correct: 1, explanation: 'A rectangle has 2 lines of symmetry; the others have just 1.' },
  { text: 'Four shapes are convex (no dents). One is concave (has a dent). Which is the odd one out?', options: ['Circle', 'Square', 'Star shape', 'Triangle'], correct: 2, explanation: 'A star shape is concave (has inward-pointing angles); the others are convex.' },
  { text: 'Four patterns show shapes increasing in size. One shows shapes decreasing. Which is the odd one out?', options: ['Small → Medium → Large', 'Tiny → Small → Medium', 'Large → Medium → Small', 'Medium → Large → Huge'], correct: 2, explanation: 'Large → Medium → Small decreases; all others increase.' },

  // -- Rotation & Reflection --
  { text: 'Which capital letter looks the same when reflected in a vertical mirror?', options: ['B', 'A', 'F', 'G'], correct: 1, explanation: 'A has a vertical line of symmetry, so it looks the same reflected vertically.' },
  { text: 'A shape is rotated 180°. Which letter still looks the same?', options: ['A', 'B', 'H', 'F'], correct: 2, explanation: 'H looks the same after a 180° rotation (it has rotational symmetry of order 2).' },
  { text: 'If you reflect the letter "b" in a vertical mirror, it becomes:', options: ['b', 'd', 'p', 'q'], correct: 1, explanation: 'Reflecting b in a vertical mirror swaps left and right, giving d.' },
  { text: 'A flag points right. After a 90° clockwise rotation, it points:', options: ['Up', 'Down', 'Left', 'Right'], correct: 1, explanation: 'Right → Down after 90° clockwise.' },
  { text: 'How many lines of symmetry does a regular pentagon have?', options: ['0', '3', '5', '10'], correct: 2, explanation: 'A regular pentagon has 5 lines of symmetry, one from each vertex.' },
  { text: 'An arrow pointing up-right is reflected in a horizontal mirror. It now points:', options: ['Up-left', 'Down-right', 'Down-left', 'Up-right'], correct: 1, explanation: 'Horizontal reflection flips up/down: up-right becomes down-right.' },
  { text: 'Which letter has exactly 2 lines of symmetry?', options: ['A', 'B', 'H', 'T'], correct: 2, explanation: 'H has both a horizontal and a vertical line of symmetry.' },
  { text: 'A shape is rotated 270° clockwise. This is the same as rotating it:', options: ['90° clockwise', '90° anticlockwise', '180°', '270° anticlockwise'], correct: 1, explanation: '270° clockwise = 360° − 90° = 90° anticlockwise.' },
  { text: 'If the letter "p" is rotated 180°, it becomes:', options: ['b', 'd', 'q', 'p'], correct: 1, explanation: 'Rotating p by 180° gives d (both flipped horizontally and vertically).' },
  { text: 'Which shape has the most lines of symmetry?', options: ['Square', 'Regular hexagon', 'Circle', 'Rectangle'], correct: 2, explanation: 'A circle has infinite lines of symmetry.' },

  // -- Folding & 3D Shapes --
  { text: 'A net has 6 identical square faces. What 3D shape does it fold into?', options: ['Cuboid', 'Cube', 'Pyramid', 'Prism'], correct: 1, explanation: 'Six identical squares fold into a cube.' },
  { text: 'A piece of paper is folded in half once and a hole is punched. When unfolded, how many holes are there?', options: ['1', '2', '3', '4'], correct: 1, explanation: 'Folding once means 2 layers. One punch = 2 holes when unfolded.' },
  { text: 'A paper is folded in half twice (4 layers) and one corner is cut off. How many corners are cut when unfolded?', options: ['1', '2', '4', '8'], correct: 2, explanation: 'Two folds = 4 layers. Cutting one corner removes it from all 4 layers.' },
  { text: 'A cube net shaped like a cross is folded up. If the bottom face is shaded, which face is shaded on the cube?', options: ['The top', 'The bottom', 'A side', 'Two faces'], correct: 1, explanation: 'The bottom of the cross becomes the bottom of the cube when folded.' },
  { text: 'How many faces does a triangular pyramid (tetrahedron) have?', options: ['3', '4', '5', '6'], correct: 1, explanation: 'A tetrahedron has 4 triangular faces.' },
  { text: 'A net has 1 square base and 4 triangular faces. What 3D shape does it make?', options: ['Cube', 'Triangular prism', 'Square-based pyramid', 'Cone'], correct: 2, explanation: '1 square + 4 triangles = square-based pyramid.' },
  { text: 'A cube has a dot on one face. The opposite face has a star. If you can see the dot, can you see the star?', options: ['Yes, always', 'No, never', 'Sometimes', 'Only if the cube is transparent'], correct: 1, explanation: 'Opposite faces of a cube can never be seen at the same time from one viewing angle.' },
  { text: 'A paper is folded in half three times. How many layers are there?', options: ['3', '6', '8', '16'], correct: 2, explanation: 'Each fold doubles the layers: 1→2→4→8.' },
  { text: 'Which of these CANNOT be a net of a cube?', options: ['A cross shape', 'A T shape', 'A straight line of 6 squares', 'An L shape of 4 squares'], correct: 3, explanation: 'An L shape of only 4 squares cannot make a cube (needs 6 squares).' },
  { text: 'A cube has red, blue, and green opposite pairs. If red is on top and blue faces you, where is green?', options: ['Left or right', 'Top', 'Bottom', 'Behind you'], correct: 0, explanation: 'Red is on top (so red is also on bottom as an opposite pair). Blue faces you (so blue is also behind). That leaves green on the left and right faces.' },

  // -- Matrices & Grids --
  { text: 'In a 3×3 grid, each row has a circle, square, and triangle. Row 3 has a circle and square. What is missing?', options: ['Circle', 'Square', 'Triangle', 'Pentagon'], correct: 2, explanation: 'Each row needs all three shapes. Circle and square are present, triangle is missing.' },
  { text: 'In a grid, shapes in each row get darker: white, grey, black. The third row has white and grey. What shade is the missing shape?', options: ['White', 'Grey', 'Black', 'Striped'], correct: 2, explanation: 'The pattern requires white, grey, black in each row. Black is missing.' },
  { text: 'In a 2×2 grid, the top-left is a small circle and top-right is a large circle. Bottom-left is a small square. What is bottom-right?', options: ['Small circle', 'Large circle', 'Small square', 'Large square'], correct: 3, explanation: 'Pattern: left=small, right=large. Top=circles, bottom=squares. So: large square.' },
  { text: 'Each row in a grid has shapes that total 4 sides. Row 1: triangle(3) + line(1). Row 2: square(4). Row 3: ?', options: ['Pentagon', 'Two triangles', 'Circle', 'Square'], correct: 3, explanation: 'Each row totals 4 sides. A square has 4 sides.' },
  { text: 'In a 3×3 grid, each column has one black, one white, and one grey shape. Column 3 has black and white. What is missing?', options: ['Black', 'White', 'Grey', 'Striped'], correct: 2, explanation: 'Each column needs all three shades. Grey is missing.' },
  { text: 'A grid shows shapes rotating 45° in each cell from left to right. The first shape points up. The 5th cell shape points:', options: ['Up', 'Down', 'Right', 'Left'], correct: 1, explanation: 'Cell 1 = 0° (up), cell 2 = 45°, cell 3 = 90° (right), cell 4 = 135°, cell 5 = 180° (down). After 4 rotations of 45° the shape has rotated 180° and points down.' },
  { text: 'In a 3×3 grid, each row and column contains exactly one of each shape: star, heart, diamond. The centre is a heart. Top-right is a diamond. What is top-left?', options: ['Star', 'Heart', 'Diamond', 'Cannot tell'], correct: 0, explanation: 'Top row needs star, heart, diamond. Centre (row 2) has heart. Top-right is diamond. Top-left must be star.' },
  { text: 'Each shape in a grid has one more side than the one above it. Top row: triangles (3 sides). What shapes are in the second row?', options: ['Triangles', 'Squares', 'Pentagons', 'Hexagons'], correct: 1, explanation: '3 sides + 1 = 4 sides = squares.' },
  { text: 'In a pattern grid, the number of dots doubles from left to right: 1, 2, 4. What comes in the 4th column?', options: ['6', '8', '16', '5'], correct: 1, explanation: 'Doubling: 1, 2, 4, 8.' },
  { text: 'A 3×3 grid has a pattern: each row shifts the shaded cell one position right. Row 1: left shaded. Row 2: centre shaded. Row 3:', options: ['Left shaded', 'Centre shaded', 'Right shaded', 'All shaded'], correct: 2, explanation: 'The shaded cell moves right each row: left → centre → right.' },

  // -- More NVR mixed --
  { text: 'A shape has exactly 4 lines of symmetry and 4 sides. What is it?', options: ['Rectangle', 'Parallelogram', 'Square', 'Rhombus'], correct: 2, explanation: 'A square has 4 lines of symmetry (2 diagonal + 2 through midpoints).' },
  { text: 'How many right angles are in a rectangle?', options: ['2', '3', '4', '6'], correct: 2, explanation: 'A rectangle has exactly 4 right angles (90° each).' },
  { text: 'A shape is reflected and then rotated 90°. The shape started as an L pointing up-right. After reflection (vertical mirror) it\'s an L pointing up-left. After 90° clockwise rotation, it points:', options: ['Down-left', 'Down-right', 'Up-right', 'Up-left'], correct: 0, explanation: 'Up-left rotated 90° clockwise becomes left-down, or equivalently down-left.' },
  { text: 'What is the order of rotational symmetry of an equilateral triangle?', options: ['1', '2', '3', '6'], correct: 2, explanation: 'An equilateral triangle looks the same 3 times during a full 360° rotation.' },
  { text: 'In a sequence, the number of sides increases by 1 and the shading alternates. Shape 1: shaded triangle. Shape 2: unshaded square. Shape 3:', options: ['Shaded pentagon', 'Unshaded pentagon', 'Shaded hexagon', 'Unshaded triangle'], correct: 0, explanation: 'Sides: 3,4,5 (pentagon). Shading: shaded, unshaded, shaded. Answer: shaded pentagon.' },
  { text: 'A cube is painted red on all faces, then cut into 27 smaller cubes (3×3×3). How many small cubes have exactly 2 red faces?', options: ['6', '8', '12', '18'], correct: 2, explanation: 'Edge cubes (not corners) have 2 painted faces. A 3×3×3 cube has 12 edge pieces.' },
  { text: 'Which shape is the reflection of a right-pointing arrow in a horizontal mirror?', options: ['Left-pointing arrow', 'Right-pointing arrow', 'Up-pointing arrow', 'Down-pointing arrow'], correct: 1, explanation: 'A horizontal mirror flips up/down, not left/right. A right-pointing arrow stays right-pointing.' },
  { text: 'A regular octagon has how many lines of symmetry?', options: ['4', '6', '8', '10'], correct: 2, explanation: 'A regular octagon has 8 lines of symmetry (same as number of sides).' },
  { text: 'In a code, shapes represent numbers: circle=1, triangle=3, square=4. What is circle + triangle + square?', options: ['7', '8', '9', '10'], correct: 1, explanation: '1 + 3 + 4 = 8.' },
  { text: 'A paper square is folded diagonally once and a semicircle is cut from the folded edge. When unfolded, what shape is the hole?', options: ['Semicircle', 'Full circle', 'Oval', 'Heart shape'], correct: 1, explanation: 'The semicircle cut on the fold becomes a full circle when the paper is unfolded.' },
  { text: 'A shape has 3 faces, 2 edges, and 0 vertices. What is it?', options: ['Cone', 'Cylinder', 'Sphere', 'Prism'], correct: 1, explanation: 'A cylinder has 3 faces (2 circular + 1 curved), 2 edges, and 0 vertices.' },
  { text: 'In a 3×3 grid, the centre shape is always the combination of the shapes in the first and third columns. Column 1 has a circle, Column 3 has a cross. The centre should be:', options: ['A circle with a cross inside', 'Just a circle', 'Just a cross', 'A square'], correct: 0, explanation: 'The centre combines both: a circle with a cross inside it.' },
  { text: 'A cube has numbers on each face: 1 opposite 6, 2 opposite 5, 3 opposite 4. If 1 is on top and 2 faces you, which number is on the right?', options: ['3', '4', '5', '6'], correct: 0, explanation: 'With 1 on top (6 bottom) and 2 facing you (5 behind), 3 is on the right and 4 on the left.' },
  { text: 'How many triangles can you see in a shape made of a triangle divided into 4 smaller triangles by connecting the midpoints?', options: ['4', '5', '6', '8'], correct: 1, explanation: '4 small triangles + 1 large outer triangle = 5 triangles total. The inverted central triangle prevents forming medium triangles from adjacent pairs.' },
  { text: 'A shape sequence shows: 1 dot, 3 dots (triangle), 6 dots (triangle), 10 dots (triangle). How many dots in the next shape?', options: ['12', '14', '15', '18'], correct: 2, explanation: 'Triangle numbers: 1, 3, 6, 10, 15. Differences increase by 1: +2,+3,+4,+5.' },
  { text: 'A net is made of 4 equilateral triangles. What 3D shape does it form?', options: ['Square-based pyramid', 'Triangular prism', 'Tetrahedron', 'Cube'], correct: 2, explanation: 'Four equilateral triangles form a tetrahedron (triangular pyramid).' },
  { text: 'In a pattern, each shape is the previous shape rotated 60°. After 6 rotations, the shape is:', options: ['90° from start', 'Back to original position', '180° from start', '120° from start'], correct: 1, explanation: '6 × 60° = 360° = full rotation, back to original position.' },
  { text: 'A 3×3 grid has numbers 1-9. Each row, column, and diagonal sums to 15. The centre number is always:', options: ['1', '3', '5', '9'], correct: 2, explanation: 'In a 3×3 magic square summing to 15, the centre is always 5.' },
  { text: 'A cube is viewed from directly above. What 2D shape do you see?', options: ['Triangle', 'Square', 'Rectangle', 'Hexagon'], correct: 1, explanation: 'Looking straight down at a cube, you see its top face: a square.' },
  { text: 'How many edges does a triangular prism have?', options: ['6', '8', '9', '12'], correct: 2, explanation: 'A triangular prism has 9 edges: 3 on each triangular face (6) + 3 connecting them.' },
];
